version: "3"
services:
  web:
    image: httpd
    container_name: web
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    image: kurraj/fluentd_castom:latest
    #image: zhopen/fluentd-es:v1.14
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/logs  
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
